version: 2
updates:
  - package-ecosystem: nuget
    directory: /src/DogDoor.Api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /src/DogDoor.Api
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /web
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
