api:
  image:
    repository: acrheathrobotics.azurecr.io/dogdoor-api
  replicas: 1
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

web:
  enabled: false

postgres:
  enabled: true

ingress:
  enabled: true
  host: dog-door-api.dev.heathrobotics.io
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: dogdoor-api-dev-tls

config:
  aspnetcoreEnvironment: Development
  corsOrigins: "https://dog-door.dev.heathrobotics.io"
