apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  PhotoStorage__BasePath: {{ .Values.config.photoStoragePath | quote }}
  {{- if .Values.config.corsOrigins }}
  Cors__AllowedOrigins__0: {{ .Values.config.corsOrigins | quote }}
  {{- end }}
