{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
  selector:
    app: {{ .Release.Name }}-web
{{- end }}
